Garments_ERP/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Garments_ERP.Service.Service;
using Garments_ERP.Entity;
using Garments_ERP.Helper;
using System.Globalization;
using Garments_ERP.Filters;
using Garments_ERP.Data.Data;

namespace Garments_ERP.Controllers
{
    public class CustomerController : SuperController
    {
        
        // GET: /Customer/
        CustomerService customerservice = ServiceFactory.GetInstance().CustomerService;
        StateService stateservice = ServiceFactory.GetInstance().StateService;
        CityService cityservice = ServiceFactory.GetInstance().CityService;
        DepartmentService departmentservice = ServiceFactory.GetInstance().DepartmentService;
        CustomerTypeService customertypeservice = ServiceFactory.GetInstance().CustomerTypeService;
        CustomerContactService customercontactservice = ServiceFactory.GetInstance().CustomerContactService;
        CustomerBankService customerbankservice = ServiceFactory.GetInstance().CustomerBankService;
        CountryService countryservice = ServiceFactory.GetInstance().CountryService;
        [RBAC]
        public ActionResult Index()
        {
            var list = customerservice.get();
            return View(list);
        }
        public ActionResult BankIndex(long? id)
        {
            var list = customerbankservice.GetById((long)id);
            return View(list);
        }
        public ActionResult ContactIndex(long? id)
        {
            var list = customercontactservice.GetById((long)id);
            return View(list);
        }

        public JsonResult Getstate(int countryid)
        {
            var statelist = stateservice.get().Where(x => x.CountryID == countryid).ToList();
            return Json(statelist);
        }
        //public JsonResult verifyGSTIN(string gstin)
        //{           
        //    //return Json();
        //}
        
        public JsonResult Getstatecode(int stateid)
        {
            var statecode = stateservice.get().Where(x => x.ID == stateid).FirstOrDefault().StateCode;
            return Json(statecode);
        }
        public JsonResult CheckCustomerName(String contactname, int? Id)
        {
            bool value = true;
            if (Id == null)
                value = customerservice.get().Where(x => x.contactname == contactname).FirstOrDefault() == null;
            else
            {

                if (customerservice.get().Where(x => x.contactname == contactname && x.Id == Id).FirstOrDefault() == null)
                {
                    if (customerservice.get().Where(x => x.contactname == contactname).FirstOrDefault() == null)
                    {
                        value = true;
                    }
                    else
                    {
                        value = false;
                    }
                }
            }

            return Json(value, JsonRequestBehavior.AllowGet);
        }

        [RBAC]
        public ActionResult Create()
        {
            ViewBag.countrylist = DropDownList<M_CountryMasterEntity>.LoadItems(countryservice.get(), "ID", "Name", 101);
            ViewBag.typelist = DropDownList<M_CustomerTypeMasterEntity>.LoadItems(customertypeservice.get(), "Id", "TypeName", 1);
            ViewBag.statelist = DropDownList<M_StateMasterEntity>.LoadItems(stateservice.get(), "ID", "Name", 1646);
            ViewBag.citylist = DropDownList<M_CityMasterEntity>.LoadItems(cityservice.getByid(1646), "ID", "Name", 0);
            ViewBag.deptlist = DropDownList<M_DepartmentMasterEntity>.LoadItems(departmentservice.get(), "Id", "Departmentname", 1);
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection frm)
        {
            var customername = frm["contactname"];
            var customertypeid = Convert.ToInt32(frm["customertypeid"]);
            var customerphone = frm["custpmerphone"];


            // var customerGSTNo = frm["GSTNo"];
            var customeremail = frm["Email"];
            var remark = frm["remark"];
            var customerCSTNo = frm["customerCSTNo"];
            var customerTINNo = frm["cutomerTINno"];

            //  var customeraddress = frm["customeraddress"];
            // var customerstateid = Convert.ToInt32(frm["customerstateid"]);
            // var customercityid = Convert.ToInt32(frm["customercityid"]);

            //customer bank details
            var customerbank = frm["customerbank"];
            var customeraccountno = frm["customeraccountno"];
            var customerbankcode = frm["customerbankcode"];
            M_CustomerMasterEntity entity = new M_CustomerMasterEntity();
            entity.contactname = customername;
            entity.Customertype = (int)customertypeid;
            entity.Phone = customerphone;

            // entity.Address = customeraddress;
            // entity.Stateid = (int)customerstateid;
            //  entity.Cityid = (int)customercityid;


            // entity.GSTNo = customerGSTNo;
            entity.Email = customeremail;
            entity.Remark = remark;
            entity.CSTRegno = customerCSTNo;
            entity.Tinno = customerTINNo;
            entity.IsActive = true;
            entity.Createddate = DateTime.Now;
            entity.Updateddate = DateTime.Now;


            //code to save contact address details
            List<M_ContactAddressEntity> addresslistentity = new List<M_ContactAddressEntity>();
            var addresslist = frm["AddressList"].ToString();
            string[] addressarr = addresslist.Split('#');
            foreach (var adress in addressarr)
            {
                string[] adresssrr = adress.Split('~');
                M_ContactAddressEntity contactaddressentity = new M_ContactAddressEntity();
                contactaddressentity.Addess = adresssrr[0];
                contactaddressentity.Stateid = Convert.ToInt16(adresssrr[1]);
                contactaddressentity.Cityid = Convert.ToInt32(adresssrr[2]);
                contactaddressentity.Countryid = Convert.ToInt32(adresssrr[3]);
                addresslistentity.Add(contactaddressentity);
            }

            entity.contactaddresslist = addresslistentity;

            long id = customerservice.Insert(entity);
            if (id > 0)
            {

                var contactslist = frm["ContactList"].ToString();
                //code to split contactlist
                string[] contactarr = contactslist.Split('#');
                foreach (var arritem in contactarr)
                {
                    string[] contact = arritem.Split('~');
                    M_CustomerContactDetailsEntity contactentity = new M_CustomerContactDetailsEntity();
                    contactentity.Customerid = id;
                    contactentity.Contactpersonname = contact[1];
                    contactentity.Mobileno = contact[2];
                    contactentity.Telephoneno = contact[3];
                    contactentity.Email = contact[4];
                    contactentity.Faxno = contact[5];
                    contactentity.Department = Convert.ToInt32(contact[6]);
                    contactentity.Remark = contact[7];
                    contactentity.IsActive = true;
                    contactentity.Createddate = DateTime.Now;
                    contactentity.Updateddate = DateTime.Now;
                    long insertedid = customercontactservice.Insert(contactentity);
                }



                //code to save customer bank details
                M_CustomerBankDetailsEntity bankentity = new M_CustomerBankDetailsEntity();
                bankentity.Customerid = id;
                bankentity.Bankcode = customerbankcode;
                bankentity.Bankname = customerbank;
                bankentity.Accountno = customeraccountno;
                bankentity.Createddate = DateTime.Now;
                bankentity.Updateddate = DateTime.Now;
                bankentity.IsActive = true;
                long insertedbankid = customerbankservice.Insert(bankentity);
                if (insertedbankid > 0)
                {
                    TempData["alertcustmsg"] = "Record Inserted Successfully.";
                    TempData["alertclass"] = "alert alert-success alert-dismissible";
                    return RedirectToAction("Index");
                }

            }
            ViewBag.typelist = DropDownList<M_CustomerTypeMasterEntity>.LoadItems(customertypeservice.get(), "Id", "TypeName", 1);
            ViewBag.statelist = DropDownList<M_StateMasterEntity>.LoadItems(stateservice.get(), "ID", "Name", 1646);
            ViewBag.citylist = DropDownList<M_CityMasterEntity>.LoadItems(cityservice.getByid(1646), "ID", "Name", 0);
            ViewBag.deptlist = DropDownList<M_DepartmentMasterEntity>.LoadItems(departmentservice.get(), "Id", "Departmentname", 1);
            return View();
        }


        [HttpPost]
        public JsonResult CreateCustomer(string custname, int _customertypeid, string custphone,  string email, string _remark, string cstno, string tinno, string bankname, string accountno, string bankcode, string contactlist, string addresslist)
        {
            if (contactlist != "" && addresslist != "")
            {
                var isinsert = false;

                var customername = custname;
                var customertypeid = _customertypeid;
                var customerphone = custphone;
                //var customeraddress = custaddress;
                // var customerstateid = stateid;
                // var customerGSTNo = gstno;
                var customeremail = email;
                var remark = _remark;
                var customerCSTNo = cstno;
                var customerTINNo = tinno;
                // var customercityid = cityid;
                //customer bank details
                var customerbank = bankname;

Garments_ERP/Views/Customer/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}


<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<link href="~/Content/Custom.css" rel="stylesheet" />
<style>
    .textcolor {
        color: white;
    }
</style>
@using (Html.BeginForm("Create", "Customer", FormMethod.Post, new { @class = "form-horizontal form-simple", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Customer Details</header>
            </div>
            @*<div class="box-header with-border">
                    <h3 class="box-title textcolor">Customer Details</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>*@
        </div>
        @Html.Partial("CustomerDetails")
    </div>

    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Contact Person Details</header>
            </div>
        </div>
        @Html.Partial("CustomerContactPerson")
    </div>


    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Contact Address Details</header>
            </div>

        </div>
        @Html.Partial("ContactAddressDetail")
    </div>

    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Bank Details</header>
            </div>

        </div>
        @Html.Partial("CustomerBank")
    </div>

    <div class="box-footer">
        <button type="button" class="btn btn btn-danger pull-right" style="margin-right:5px;" onclick="location.href='@Url.Action("Index", "Customer")'">Cancel</button>
        <button type="submit" class="btn btn pull-right" style="margin-right:5px;" id="saveCustomer">Save</button>
    </div>
}
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="@Url.Content("~/Content/bower_components/select2/dist/js/select2.full.min.js")"></script>
<script src="~/Scripts/SaveCustomer.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>

    $(document).ready(function () {
        $('.select2').select2();
        $('.select2').width("100%");
        $('#customergstno').val("27");
        $('#statecodehidden').val("27");
    });

    function getState() {
        $("#addressstateid").empty();
        var countryid = $("#countryid").val();
        if (countryid != "0" && countryid != "") {
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("Getstate", "Customer")',
                dataType: "json",
                data: "{'countryid':" + countryid + "}",
                success: function (states) {
                    $.each(states, function (i, item) {
                        $("#addressstateid").append('<option value="' + item.ID + '">' + item.Name + '</option>');

                    });
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });
        }
    }


    function getCity() {
        $("#addresscityid").empty();
        var stateid = $("#addressstateid").val();
        if (stateid != "" && stateid != "0") {
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("getCityNameList", "Supplier")',
                dataType: "json",
                data: "{'stateid':" + stateid + "}",
                success: function (citys) {
                    $.each(citys, function (i, city) {
                        $("#addresscityid").append('<option value="' + city.ID + '">' + city.Name + '</option>');

                    });
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });


            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("Getstatecode", "Customer")',
                dataType: "json",
                data: "{'stateid':" + stateid + "}",
                success: function (result) {
                    //$('#customergstno').val(result);
                    $('#statecodehidden').val(result);
                    setGSTno();
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });
        }


    }
    function checkEmail() {
        var emailstr = $("#customeremail").val();
        if (emailstr != "") {
            var id = 0;
            var param = { 'strEmail': emailstr, 'Id': id }
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("IsEmailExist", "Customer")',
                dataType: "json",
                data: JSON.stringify(param),
                success: function (value) {
                    if (value == false) {
                        swal({
                            title: "Email already exist!",
                            type: "warning",
                            showCancelButton: false,
                            confirmButtonText: "OK",
                            closeOnConfirm: false
                        }, function (isConfirm) {
                            if (isConfirm) {
                                swal.close();
                                $("#customeremail").val("");
                            }
                        })
                    }
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });
        }
    }
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }

    function verifyGSTIN() {
        var gstin = $("#customergstno").val();
        if (gstin != "") {
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("verifyGSTIN", "Customer")',
                dataType: "json",
                data: "{'gstin':" + gstin + "}",
                success: function (result) {
                    if (result == true) {

                    }
                    else {

                    }
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });
        }

    }
</script>

Garments_ERP/Views/Customer/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}
<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<style>

    .textcolor {
        color: white;
    }
</style>
@using (Html.BeginForm("Edit", "Customer", FormMethod.Post, new { @class = "form-horizontal form-simple", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Customer Details</header>
            </div>
        </div>
        @Html.Partial("EditCustomerDetails")
    </div>
    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Contact Person Details</header>
            </div> 
         </div>
            @Html.Partial("EditCustomerContactPerson")
        </div>

    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Contact Address Details</header>
            </div>  
        </div>
        @Html.Partial("EditContactAddressDetail")
    </div>

    <div class="box box-default">
        <div class="titlerow bg-light-blue">
            <div class="with-border panelHeader">
                <header class="box-title">Bank Details</header>
            </div> 
        </div>
            @Html.Partial("EditCustomerBank")
        </div>
    <div class="box-footer">
        <button type="button" class="btn btn btn-danger pull-right" style="margin-right:5px;" onclick="location.href='@Url.Action("Index", "Customer")'">Cancel</button>
        <button type="submit" class="btn btn pull-right" style="margin-right:5px;" id="saveCustomer">Update</button>
    </div>
}
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="@Url.Content("~/Content/bower_components/select2/dist/js/select2.full.min.js")"></script>
<script src="~/Scripts/SaveCustomer.js"></script>
@*<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
<script>

    function getState() {
        $("#addressstateid").empty();
        var countryid = $("#countryid").val();
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("Getstate", "Customer")',
            dataType: "json",
            data: "{'countryid':" + countryid + "}",
            success: function (states) {
                $.each(states, function (i, item) {
                    $("#addressstateid").append('<option value="' + item.ID + '">' + item.Name + '</option>');

                });
            },
            error: function (result) {
                alert("Error" + result.status);
            }
        });
    }
    function getCity() {
        $("#addresscityid").empty();
        var stateid = $("#addressstateid").val();
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: '@Url.Action("getCityNameList", "Supplier")',
            dataType: "json",
            data: "{'stateid':" + stateid + "}",
            success: function (citys) {
                $.each(citys, function (i, city) {
                    $("#addresscityid").append('<option value="' + city.ID + '">' + city.Name + '</option>');
                });
            },
            error: function (result) {
                alert("Error" + result.status);
            }
        });
    }
    function checkEmail() {
        var emailstr = $("#customeremail").val();
        if (emailstr != "") {
            var id = $("#Id");
            var param = { 'strEmail': emailstr, 'Id': id }
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: '@Url.Action("IsEmailExist", "Customer")',
                dataType: "json",
                data: JSON.stringify(param),
                success: function (value) {
                    if (value == false) {
                        swal({
                            title: "Email already exist!",
                            type: "warning",
                            showCancelButton: false,
                            confirmButtonText: "OK",
                            closeOnConfirm: false
                        }, function (isConfirm) {
                            if (isConfirm) {
                                swal.close();
                                $("#customeremail").val("");
                            }
                        })
                    }
                },
                error: function (result) {
                    alert("Error" + result.status);
                }
            });
        }
    }
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
    function setGSTtype() {
        var regtype = $('#customertypeid').val();
        if (regtype == "1") {
            $('#gstno').show();
        }
        else {
            $('#gstno').hide();
        }
    }
</script>

Garments_ERP/Views/Customer/EditContactAddressDetail.cshtml
@model Garments_ERP.Entity.M_CustomerMasterEntity


<div class="box-body">
    <div class="row">

        <div class="col-md-12">
            <div class="col-md-2">
                <label>Address<i class="text-red">*</i></label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="text" height="40" class="form-control" id="address" name="contactperson" maxlength="50" />
                </div>
            </div>
            <div class="col-md-2">
                <label>Country<i class="text-red">*</i></label>
            </div>
            <div class="col-md-4">
                <div class="form-group">

                    @Html.DropDownList("countryid", (IEnumerable<SelectListItem>)ViewBag.countrylist, "---Select Country---", new { @class = "form-control select2", @onchange = "getState()" })
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-2">
                <label>State<i class="text-red">*</i></label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.DropDownList("addressstateid", (IEnumerable<SelectListItem>)ViewBag.statelist, "---Select State---", new { @class = "form-control select2", @onchange = "getCity()" })
                </div>
            </div>

            <div class="col-md-2">
                <label>City<i class="text-red">*</i></label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.DropDownList("addresscityid", (IEnumerable<SelectListItem>)ViewBag.citylist, "---Select City---", new { @class = "form-control select2" })
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-2">
                <label>GST No</label>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.TextBoxFor(m => m.GSTNo, new { @class = "form-control", @id = "CustomerGSTNo", @style = "text-transform: uppercase", @maxLength = "15" })
                    @Html.ValidationMessageFor(model => model.GSTNo, "", new { @class = "text-red" })

                </div>
            </div>
        </div>


    </div>
</div>

<div class="box-footer">
    <button type="button" class="btn btn-info pull-left" style="margin-right:5px;" id="addaddress" onclick="addaddressdetail()">Add More</button>
</div>
<input type="hidden" id="AddressList" name="AddressList" />

<div class="box-footer">
    <div class="table-responsive">
        <table class="table" id="contactaddresstable">
            <thead>
                <tr class="titlerow bg-blue">
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>

                    <th>Action</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="contactaddresstablebody">
                @{
                    var i=0;
                }
                @foreach(var item in Model.contactaddresslist)
                {
                   i++;
                    var unid="unid"+i;
                    var row = "row" + i;
                   var addressid = "addressid_" + i;
                   var cityid = "city" + i;
                   var stateid = "state" + i;
                   var countryid = "country" + i;
                    <tr id=@row>
                        <td style="display:none;"><input type="hidden" value=@item.Id id=@unid /></td>
                        <td id=""><input type="text" class="form-control" id=@addressid value=@item.Addess /></td>
                         <td>@Html.DropDownListFor(model => item.Cityid, new SelectList(Model.citylist,"ID", "Name",(int)item.Cityid), new { @class = "form-control select2", @id = @cityid })</td>
                        <td id="">@Html.DropDownListFor(model => item.Stateid, new SelectList(Model.statelist, "ID", "Name", (int)item.Stateid), new { @class = "form-control select2", @id = @stateid })</td>
                        <td id="">@Html.DropDownListFor(model => item.Countryid, new SelectList(Model.countrylist, "ID", "Name", (int)item.Countryid), new { @class = "form-control select2", @id = @countryid })</td>
                        <td><button type="button"  id=@i onclick="editaddressdetail(this.id)" class="btn bg-blue">Edit</button></td>
                        <td><button type="button" id=@i onclick="deleteaddressdetail(this.id)" class="btn bg-danger">Remove</button> </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script>
    function editaddressdetail(id)
    {
        var number = id.match(/\d+/);

        var uid = $('#unid' + number).val();
        var addressval = $('#addressid_' + number).val();
        var cityid = $('#city' + number).val();
        var stateid = $('#state' + number).val();
        var countryid = $('#country' + number).val();

        var param = {
            'id': uid, 'address': addressval, 'cityid': cityid, 'stateid': stateid,'countryid':countryid};
        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateAddressdetail", "Customer")',
            data: JSON.stringify(param),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                // alert("in success inserted");
                if (result == true) {
                    swal(" record updated");

                }

            },
            failure: function (response) {
                alert(response.d);
            }
        });
    }
    function deleteaddressdetail(id) {
        var number = id.match(/\d+/);

        var uid = $('#unid' + number).val();
       


        var param = {
            'id': uid
        };
        $.ajax({
            type: "POST",
            url: '@Url.Action("deleteaddress", "Customer")',
            data: JSON.stringify(param),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                // alert("in success inserted");
                if (result == true) {
                    swal(" record deleted");
                    $('table#contactaddresstable tr#row'+number).remove();
                    
                }

            },
            failure: function (response) {
                alert(response.d);
            }
        });


    }


    function addaddressdetail()
    {
        var rowCount = 0;
        var cityid = $('#addresscityid').val();
        var citytext=$("#addresscityid option:selected").text();

        var stateid = $('#addressstateid').val();
        var statetext=$("#addressstateid option:selected").text();
        var countryid = $('#countryid').val();
        var countrytext = $("#countryid option:selected").text();
        var addressstr = $('#address').val();
        if(addressstr=="")
        {
            swal("enter address")
        }
        else if(cityid=="0" && cityid=="")
        {
            swal("select city")
        }
        else if (stateid == "0" && stateid == "") {
            swal("select state")
        }
        else if (countryid == "0" || countryid == "") {
            swal("select country");
        }
        else {
            var div = '<tr><td style="padding-right:10px;" rawdata="' + addressstr + '" class="addressrow"><p>' + addressstr + '</p></td>' +
                  '<td style="padding-right:10px;" class="addressrow" rawdata="' + stateid + '"><p>' + statetext + '</p></td>' +
                  '<td style="padding-right:10px;" class="addressrow" rawdata="' + cityid + '"><p>' + citytext + '</p></td>' +
                   '<td style="padding-right:10px;" class="addressrow" rawdata="' + countryid + '"><p>' + countrytext + '</p></td>' +
                  '<td><button type="button" id="btnDelete" class="deleterawitem btn btn btn-danger btn-xs">Remove</button></td></tr>'

            $('#contactaddresstable').append(div);
        }

    }

    $(document).on("click", ".deleterawitem", function () {
        var id = $(this).closest("tr").attr('data');
        // alert(id);
        $(this).closest("tr").remove(); // closest used to remove the respective 'tr' in which I have my controls

       // $('table#hiderawitemtable tr#' + id).remove();

    });



</script>