Garments_ERP/Controllers/JobworkController.cs
using Garments_ERP.Data.Data;
using Garments_ERP.Entity;
using Garments_ERP.Filters;
using Garments_ERP.Helper;
using Garments_ERP.Service.Service;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garments_ERP.Controllers
{
    public class JobworkController : SuperController
    {
        //
        // GET: /Jobwork/
        WorkorderService workorderservice = ServiceFactory.GetInstance().WorkorderService;
        JobWorkService jobworkservice = ServiceFactory.GetInstance().JobWorkService;
        SRM_GRNInwardService srmgrnservice = ServiceFactory.GetInstance().SRMGRNInwardService;
        UnitService unitservice = ServiceFactory.GetInstance().UnitService;

        [RBAC]
        public ActionResult Index()
        {
            ViewBag.title = "Job Work";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;

            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);
            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);
            return View();
        }

        [RBAC]
        public ActionResult Create()
        {
            ViewBag.title = "Job Work";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;

            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);
            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);
            ViewBag.ControlList = DropDownList<M_Dynamic_ControlsEntity>.LoadItems(srmgrnservice.GetControlList(), "Dynamic_Controls_Id", "Control_Name", 0);
            ViewBag.workordernolist = DropDownList<MFG_WORK_ORDEREntity>.LoadItems(workorderservice.Get().Where(x => x.Company_ID == ViewBag.companyid && x.BranchId == ViewBag.branchid && x.IsStatus == 3).ToList(), "WorkOrderID", "WorkOrderNo", 0);
            M_JobworkEntity entity = new M_JobworkEntity();
            string[] jobno = jobworkservice.getnextJWNo().Split('-');
            entity.jobworkno = jobno[0] + "-" + jobno[1] + "-" + jobno[2] + "-" + jobno[3] + "-XXXX";
            return View(entity);
        }

        [RBAC]
        [HttpPost]
        public ActionResult Create(M_JobworkEntity entity, FormCollection frm)
        {
            try
            {
                var sessiondat = Session["LoggedUser"];
                M_UserEntity collection = (M_UserEntity)sessiondat;

                int roleid = Convert.ToInt32(collection.RoleID);
                int deptid = Convert.ToInt32(collection.DeptID);
                int userid = Convert.ToInt32(collection.Id);
                int companyid = Convert.ToInt32(collection.Company_ID);
                int branchid = Convert.ToInt32(collection.BranchId);

                entity.processInchargeId = Convert.ToInt64(userid);
                entity.woid = Convert.ToInt64(frm["woid"]);
                entity.transferId = Convert.ToString(frm["TransferNo"]);
                entity.JobStatus = Convert.ToString(frm["jobstatus"]);
                string startdate = Convert.ToString(frm["startdate"]);
                DateTime JBstartDate = DateTime.ParseExact(startdate, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                entity.startjobdate = JBstartDate;
                entity.startjobtime = Convert.ToString(frm["starttime"]);
                string Enddate = Convert.ToString(frm["enddate"]);
                DateTime JBEndDate = DateTime.ParseExact(Enddate, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                entity.endjobtime = Convert.ToString(frm["endtime"]);
                entity.MachineId = Convert.ToInt64(frm["MachineId"]);
                entity.ProcessId = Convert.ToInt64(frm["ProcessId"]);
                entity.OutItemName = Convert.ToInt64(frm["outItemid"]);
                entity.outAttributeId = Convert.ToInt64(frm["outItemAttribId"]);
                entity.OutQty = Convert.ToDecimal(frm["outItemQty"]);
                entity.CreatedBy =Convert.ToString(userid);
                entity.Company_ID = companyid;
                entity.BranchId = branchid;
                entity.IsStatus = 3;

                string itemdata = Convert.ToString(frm["jbrawmaterial"]);
                if (itemdata != "")
                {
                    string[] spltdata = itemdata.Split('#');
                    List<M_Jobwork_MaterialEntity> Material = new List<M_Jobwork_MaterialEntity>();
                    foreach (var item in spltdata)
                    {
                        if (item != "")
                        {
                            string[] rawitem = item.Split('~');
                            M_Jobwork_MaterialEntity ent = new M_Jobwork_MaterialEntity();
                            ent.ItemId = Convert.ToInt64(rawitem[0]);
                            ent.ItemAttributeId = Convert.ToInt32(rawitem[1]);
                            ent.unitid = Convert.ToInt64(rawitem[2]);
                            ent.BatchId = Convert.ToInt64(rawitem[3]);
                            ent.BatchQty = Convert.ToDecimal(rawitem[4]);
                            ent.ConsumedQty = Convert.ToDecimal(rawitem[5]);
                            ent.BalanceQty = Convert.ToDecimal(rawitem[6]);
                            ent.BalanceQty = Convert.ToDecimal(rawitem[6]);
                            ent.CreatedBy =Convert.ToString(userid);
                            ent.Company_ID = companyid;
                            ent.BranchId = branchid;
                            Material.Add(ent);

                        }
                    }
                    entity.JBmaterial = Material;

                    long id = jobworkservice.Insert(entity);

                    if (id > 0)
                    {
                        TempData["alertmsg"] = "Record Added Successfully.";
                        TempData["alertclass"] = "alert alert-success alert-dismissible";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["alertmsg"] = "Something Wrong..!";
                    TempData["alertclass"] = "alert alert-success alert-dismissible";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                Helper.ExceptionLogging.SendErrorToText(ex);
                TempData["alertmsg"] = ex.Message;
                TempData["alertclass"] = "alert alert-success alert-dismissible";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        [RBAC]
        public ActionResult Edit(long id)
        {
            ViewBag.title = "Job Work";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;
            M_JobworkEntity entity = new M_JobworkEntity();
            entity = jobworkservice.GetById(id);
            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);

            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);

            ViewBag.ControlList = DropDownList<M_Dynamic_ControlsEntity>.LoadItems(srmgrnservice.GetControlList(), "Dynamic_Controls_Id", "Control_Name", 0);
            ViewBag.workordernolist = DropDownList<MFG_WORK_ORDEREntity>.LoadItems(workorderservice.Get().Where(x => x.Company_ID == ViewBag.companyid && x.BranchId == ViewBag.branchid && x.IsStatus == 3).ToList(), "WorkOrderID", "WorkOrderNo", (int)entity.woid);
            ViewBag.itemunitlist = DropDownList<M_UnitMasterEntity>.LoadItems(unitservice.get(), "Id", "ItemUnit", 0);

            return View(entity);
        }

        [RBAC]
        [HttpPost]
        public ActionResult Edit(M_JobworkEntity entity, FormCollection frm)
        {
            try
            {
                var sessiondat = Session["LoggedUser"];
                M_UserEntity collection = (M_UserEntity)sessiondat;

                int roleid = Convert.ToInt32(collection.RoleID);
                int deptid = Convert.ToInt32(collection.DeptID);
                int userid = Convert.ToInt32(collection.Id);
                int companyid = Convert.ToInt32(collection.Company_ID);
                int branchid = Convert.ToInt32(collection.BranchId);
                bool isupdate = false;
                using (var db = new GarmentERPDBEntities())
                {
                    long inwarditemid = Convert.ToInt64(frm["jobid"]);
                    string itemPIval = Convert.ToString(frm["productinfo"]);
                    string itemPIId = Convert.ToString(frm["producttype"]);
                    if (itemPIval != "" && itemPIId != "")
                    {
                        string[] itemPI = itemPIval.Split('#');
                        string PIids = itemPIId;

                        foreach (var myPIdata in itemPI)

Garments_ERP/Views/Jobwork/Index.cshtml
@model IEnumerable<Garments_ERP.Entity.M_JobworkEntity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}


<style>
    .inner {
        display: inline-block;
    }

    .modal-ku {
        width: 750px;
        margin: auto;
    }
    .loader_img {
        text-align: center;
        min-height: 100px;
        padding-top: 50px;
    }
</style>

<style>
    #footerExport td {
        cursor: pointer;
        text-align: center;
        border: 1px solid #ccc;
        border: none;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>

<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<script src="~/Content/exportpugin/tableExport.js"></script>
<script src="~/Content/exportpugin/jquery.base64.js"></script>
<script src="~/Content/exportpugin/html2canvas.js"></script>
<script src="~/Content/exportpugin/jspdf/libs/base64.js"></script>
<script src="~/Content/exportpugin/jspdf/libs/sprintf.js"></script>
<script src="~/Content/exportpugin/jspdf/jspdf.js"></script>
<script src="~/Scripts/JqueryUI.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/SelTab.css" rel="stylesheet" />
<link href="~/Content/datepickercs.css" rel="stylesheet" />

<div style="display:none;" id="divLoadingContent">
    <div id="CoilMappingloader" class="loader_img">
        <img src="~/Images/loader.gif" class="loading-img " />
    </div>
</div>

<div class="titheader">
    <div class="block-header">
        <div class="col-sm-10">
            <div class="HMline"><a href="@Url.Action("Index", "Dashboard")">Production Planning</a>  >  </div>
            <div class="HMsubline">Job Work Details</div>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-block btn-success btn-sm" href="@Url.Action("Create", "Jobwork")">Create Job Work</a>
        </div>

    </div>
</div>

@using (Html.BeginForm("Index", "Jobwork", FormMethod.Post))
{
    <section class="content">
        <div class="container-fluid">
            <!-- #END# Hover Expand Effect -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="col-xs-12 col-sm-3">
                                <h2 class="hedtit">
                                    Job Work Details
                                </h2>
                            </div>

                            <div class="col-xs-6 col-sm-3">
                                <h4 class="card-inside-title">From Date</h4>
                                <div class="input-group date " id="bs_datepicker_component_container">
                                    <div class="form-line">
                                        @if (@ViewBag.fromdate != null)
                                        {
                                            <input type="text" class="form-control" placeholder="From Date" id="fromdate" autocomplete="off" name="fromdate" value=@Convert.ToString(string.Format("{0:MM/dd/yyyy}", @ViewBag.fromdate))>
                                        }
                                        else
                                        {
                                            <input type="text" class="form-control" id="fromdate" autocomplete="off" name="fromdate">
                                        }
                                    </div>
                                    <span class="input-group-addon">
                                        <i class="material-icons">date_range</i>
                                    </span>
                                </div>
                            </div>

                            <div class="col-xs-6 col-sm-3">
                                <h4 class="card-inside-title">To Date</h4>
                                <div class="input-group date" id="bs_datepicker_component_container1">
                                    <div class="form-line">
                                        @if (@ViewBag.todate != null)
                                        {
                                            <input type="text" class="form-control" placeholder="To Date" id="todate" autocomplete="off" name="todate" value=@Convert.ToString(string.Format("{0:MM/dd/yyyy}", @ViewBag.todate))>
                                        }

                                        else
                                        {
                                            <input type="text" class="form-control" id="todate" name="todate" autocomplete="off">
                                        }
                                    </div>
                                    <span class="input-group-addon">
                                        <i class="material-icons">date_range</i>
                                    </span>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-3">
                                <button type="button" class="btn btn-info btn-sm" onclick="FilterDataShow()">Show</button>
                                <button type="button" class="btn btn-info btn-sm" onclick="RefreshPage()">Refresh</button>
                            </div>
                        </div>
                        <div class="body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#InProgress" data-toggle="tab" onclick="GetData(3,'InProgress')">
                                        <i class="material-icons">hourglass_empty</i> In-Progress  (<label id="InProgresscount" name="InProgresscount">0</label>)
                                    </a>
                                </li>
                                <li role="presentation">
                                    <a href="#Completed" data-toggle="tab" onclick="GetData(4,'Completed')">
                                        <i class="material-icons">check_circle_outline</i> Completed  (<label id="Completedcount" name="Completedcount">0</label>)
                                    </a>
                                </li>

                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content" id="Tablist">

                                <div role="tabpanel" class="tab-pane fade in active" id="InProgress" datavalue="3">
                                    
                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="Completed" datavalue="4">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}


<input type="hidden" id="altmsg" value="@Convert.ToString(TempData["alertmsg"])" />


<script src=@Url.Content("~/Content/bower_components/jquery/dist/jquery.min.js")></script>
<script src="@Url.Content("~/Content/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")"></script>

<script>
    $(function () {

        $("#bs_datepicker_component_container > .ui-datepicker-inline").attr('style', 'display:none;');
        $("#bs_datepicker_component_container1 > .ui-datepicker-inline").attr('style', 'display:none;');

      
        $("#Completedtab").parent().attr("style", "overflow-x:scroll;");
        $("#InProgresstab").parent().attr("style", "overflow-x:scroll;");



        GetData(3, 'InProgress');

        debugger;
        var alrtmsg = $("#altmsg").val();
        if (alrtmsg != "") {
            swal({
                title: 'Success',
                text: alrtmsg,
                type: "success",
                showCancelButton: false,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ok",
                closeOnConfirm: false,
                closeOnCancel: false

            });
        }


        var param = { 'Type': 13,'attribute':''};
        $.ajax({
            type: "POST",
            url: '@Url.Action("StatusCount", "CustomerEnquiry")',
            data: JSON.stringify(param),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (result) {
                result = JSON.parse(result);
                $.each(result.Table, function (i, data) {
                    $("#InProgresscount").text(data.inprogress);
                    $("#Completedcount").text(data.completed);
                });
            },
            failure: function (response) {
                         alert(response.d);
            }
         });


        

    });

    $('#bs_datepicker_component_container').datepicker({
        autoclose: true,
        container: '#bs_datepicker_component_container'
    });

    $('#bs_datepicker_component_container1').datepicker({
        autoclose: true,
        container: '#bs_datepicker_component_container1'
    });


    function deleterecord(id) {
        var deletionid = id;
        var param = { 'Id': deletionid };

        swal({
            title: 'Confirmation',
            text: 'Are you sure to delete this transfer?',
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Confirm',
            confirmButtonColor: '#8CD4F5',
            cancelButtonText: 'Cancel'
        },
         function (isConfirm) {

             if (isConfirm) {
                 $.ajax({
                     type: "POST",
                     url: '@Url.Action("DeleteTransfer", "Transfer")',
                     data: JSON.stringify(param),
                     contentType: "application/json; charset=utf-8",
                     dataType: "json",
                     success: function (result) {

                         if (result == true) {
                             window.location.reload();
                             swal("Record deleted successfully.");
                         }

                     },
                     failure: function (response) {
                         alert(response.d);
                     }
                 });

             } else {
                 swal("Cancelled", ")", "error");
             }
         });
    }


    function GetData(Status, Name) {
        
        $("#Completed").empty();
        $("#InProgress").empty();

        $("#" + Name).html(loadingHTML());
        $("#" + Name).load("@Url.Action("GetStatusData", "Jobwork")", { 'IsStatus': Status});
        
    }

    function loadingHTML() {
        return $("#divLoadingContent").html();
    }


    function setDateformat(Dt) {
        debugger;
        var today = "";
        if (Dt != "" && Dt != null) {
            var dt1 = Dt.substring(6, Dt.length);
            dt1 = dt1.substring(0, dt1.length - 2);
            today = new Date(parseInt(dt1));
            var dd = today.getDate();
            var mm = today.getMonth() + 1; //January is 0!
            // var today2 = today.setMonth(mm + 1);
            var yyyy = today.getFullYear();
            if (dd < 10) {
                dd = '0' + dd;
            }
            if (mm < 10) {
                mm = '0' + mm;
            }
            today = mm + '/' + dd + '/' + yyyy;
        }
        return today;
    }

    function FilterDataShow() {
        debugger;
        var formDate = $("#fromdate").val();
        var toDate = $("#todate").val();
        var Name = $("#Tablist > .active").attr('id');
        var Status = $("#" + Name).attr("datavalue");
        
        $("#Completed").empty();
        $("#InProgress").empty();

        $("#" + Name).html(loadingHTML());
        $("#" + Name).load("@Url.Action("GetFilterStatusData", "Jobwork")", { 'fromdate': formDate, 'todate': toDate, 'IsStatus': Status});

    }


</script>

Garments_ERP/Views/Jobwork/_IndexList.cshtml
@model IEnumerable<Garments_ERP.Entity.M_JobworkEntity>
@{
    ViewBag.Title = "Index";
}
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="example1" style="width:200%;">
        <thead>
            <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 181px;">
                    Job Work No
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Work Order No
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Process Name
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Machine Name
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Material Transfer No
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Job Status
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Job Start Date
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Job Start Time
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Job End Date
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Job End Time
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Out Item Name
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Out Qty
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Accept Qty
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                    Is QC
                </th>
                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 154px;">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var data in Model)
            {
                var status = data.JobStatus == "1" ? "Start" : "END";
                <tr role="row" class="odd">
                    <td class="sorting_1">@data.jobworkno</td>
                    <td>@data.WOEntity.WorkOrderNo</td>
                    <td>@data.ProcessEntity.SHORT_NAME</td>
                    <td>@data.machineEntity.Machinename</td>
                    <td>@data.TransferEntity.STOCK_TRANSFER_NO</td>
                    <td>@status</td>
                    <td>
                        @{
                            string tndt = Convert.ToString(string.Format("{0:MM/dd/yyyy}", data.startjobdate));
                            tndt = tndt.Replace('-', '/');
                        }
                        @tndt
                    </td>
                    <td>@data.startjobtime</td>
                    <td>
                        @{
                            string tndt1 = Convert.ToString(string.Format("{0:MM/dd/yyyy}", data.endjobdate));
                            tndt1 = tndt1.Replace('-', '/');
                        }
                        @tndt1
                    </td>
                    <td>@data.endjobtime</td>
                    <td>@data.ItemEntity.ItemName</td>
                    <td>@data.OutQty</td>
                    <td>@data.AcceptQty</td>
                    <td>@data.QC </td>
                    <td>
                        <a href="@Url.Action("Edit", "Jobwork", new { id = data.jobworkid})" class="btn  btn-success btn-sm inner " data-original-title="Edit Job work" style="padding:2px 7px 5px 7px;border-radius: 4px;margin-bottom: 4px;">IsQC </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<script>
    $(document).ready(function () {
        $('#example1').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': false,
            "order": [[0, "desc"]],
            "dom": 'Bfrtip',
            "buttons": [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>