Garments_ERP/Controllers/DiscountTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Garments_ERP.Service.Service;
using Garments_ERP.Entity;
using Garments_ERP.Helper;
using Garments_ERP.Filters;

namespace Garments_ERP.Controllers
{
    public class DiscountTypeController : SuperController
    {
        //
        // GET: /DiscountType/
        DiscountTypeService discounttypeservice = ServiceFactory.GetInstance().DiscountTypeService;

        [RBAC]
        public ActionResult Index()
        {
            ViewBag.title = "Discount Type";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;

            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);
            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);

            var list = discounttypeservice.get();
            return View(list);
        }

        [RBAC]
        public ActionResult Create()
        {
            ViewBag.title = "Discount Type";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;

            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);
            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);

            return View();
        }

        [RBAC]
        [HttpPost]
        public ActionResult Create(M_DiscountTypeMasterEntity entity)
        {
            
                try
                {
                    if (ModelState.IsValid)
                    {
                        entity.IsActive = true;
                        //New Code Added by Rahul on 09-01-2020
                        var sessiondat = Session["LoggedUser"];
                        M_UserEntity collection = (M_UserEntity)sessiondat;
                        entity.CreatedBy = Convert.ToInt32(collection.Id);
                        entity.CreatedDate = DateTime.Now;
                        entity.Company_ID = Convert.ToInt32(collection.Company_ID);
                        entity.Branch_ID = Convert.ToInt32(collection.BranchId);

                        long id = discounttypeservice.Insert(entity);
                        if (id > 0)
                        {

                            TempData["alertmsg"] = "Record Save Successfully.";
                            TempData["alertclass"] = "alert alert-success alert-dismissible";
                            return RedirectToAction("Index");
                        }
                    }
                }
                catch (Exception ex)
                {
                    Helper.ExceptionLogging.SendErrorToText(ex);
                    TempData["alertmsg"] = ex.Message;
                    TempData["alertclass"] = "alert alert-success alert-dismissible";
                    return RedirectToAction("Index");
                }
            
            return RedirectToAction("Index");
        }
         
        [RBAC]
        public ActionResult Edit(int id)
        {
            ViewBag.title = "Discount Type";
            var sessiondat = Session["LoggedUser"];
            M_UserEntity collection = (M_UserEntity)sessiondat;

            ViewBag.roleid = Convert.ToInt32(collection.RoleID);
            ViewBag.deptid = Convert.ToInt32(collection.DeptID);
            ViewBag.userid = Convert.ToInt32(collection.Id);
            ViewBag.companyid = Convert.ToInt32(collection.Company_ID);
            ViewBag.branchid = Convert.ToInt32(collection.BranchId);
            ViewBag.EmpName = Convert.ToString(collection.empentity.Name);
            ViewBag.Username = Convert.ToString(collection.Username);

            M_DiscountTypeMasterEntity entity = discounttypeservice.get().Where(x => x.Id == id).FirstOrDefault();
            return View(entity);
        }

        [RBAC]
        [HttpPost]
        public ActionResult Edit(M_DiscountTypeMasterEntity entity)
        {
            
                try
                {
                    if (ModelState.IsValid)
                    {
                        var sessiondat = Session["LoggedUser"];
                        M_UserEntity collection = (M_UserEntity)sessiondat;
                        entity.UpdatedBy = Convert.ToInt32(collection.Id);
                        entity.UpdatedDate = DateTime.Now;
                        entity.Company_ID = Convert.ToInt32(collection.Company_ID);
                        entity.Branch_ID = Convert.ToInt32(collection.BranchId);

                        bool isupdate = discounttypeservice.Update(entity);
                        if (isupdate == true)
                        {
                            M_StyleMasterEntity entity_ = new M_StyleMasterEntity();
                            var list = discounttypeservice.get();
                            TempData["alertmsg"] = "Record Updated Successfully.";
                            TempData["alertclass"] = "alert alert-success alert-dismissible";
                            return RedirectToAction("Index");
                        }
                    }
                }
                catch (Exception ex)
                {
                    Helper.ExceptionLogging.SendErrorToText(ex);
                    TempData["alertmsg"] = ex.Message;
                    TempData["alertclass"] = "alert alert-success alert-dismissible";
                    return RedirectToAction("Index");
                }
            
            return RedirectToAction("Index");
        }
        
        [RBAC]
        public ActionResult Delete(int id)
        {
            bool delete = discounttypeservice.Delete(id);
            if (delete == true)
            {
                return Json(delete);
            }
            return Json(delete);
        }

        public JsonResult CheckDiscountType(string DiscountTypeName, int? Id)
        {
            bool value = discounttypeservice.CheckDiscountTypeNameExistance(DiscountTypeName, Id);
            return Json(value, JsonRequestBehavior.AllowGet);
        }

    }
}

Garments_ERP/Views/DiscountType/Create.cshtml
@model Garments_ERP.Entity.M_DiscountTypeMasterEntity
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>>
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<script src="~/Scripts/JqueryUI.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/SelTab.css" rel="stylesheet" />
<link href="~/Content/datepickercs.css" rel="stylesheet" />

@using (Html.BeginForm("Create", "DiscountType", FormMethod.Post, new { @class = "form-horizontal form-simple", enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="titheader">
        <div class="block-header">
            <div class="col-sm-10">
                <div class="HMline"><a href="@Url.Action("Index", "Dashboard")">CSI Master</a>  >  </div>
                <div class="HMline"><a href="@Url.Action("Index", "DiscountType")">Discount Type Detail</a>  >  </div>
                <div class="HMsubline">Create</div>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-success pull-left" style="margin-right:5px;" id="savedistype">Save</button>
                <button type="button" class="btn btn-danger pull-left" style="margin-right:5px;" id="btncancel" onclick="location.href='@Url.Action("Index", "DiscountType")'">Cancel</button>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <!-- #END# Hover Expand Effect -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#home_with_icon_title" data-toggle="tab">
                                        <i class="material-icons">home</i> Discount Type Info
                                    </a>
                                </li>

                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade in active" id="home_with_icon_title">
                                    @Html.Partial("CreateDiscountType")
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


}
<script src="~/Scripts/select2.min.js"></script>
<script src=@Url.Content("~/Content/bower_components/jquery/dist/jquery.min.js")></script>
<script src="@Url.Content("~/Content/bower_components/select2/dist/js/select2.full.min.js")"></script>
<script src="@Url.Content("~/Content/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")"></script>


<script src="~/Scripts/SaveCustomer.js"></script>

<script>

    $(document).ready(function () {
        $("#bs_datepicker_component_container > .ui-datepicker-inline").attr("style", "Display:none;");
        $('.select2').select2();
        $('.select2').width("100%");
    });


            $('#savedistype').on("click", function () {
                var isvalid = true;
                var distcname = $('#DiscountTypeName').val();

                if (distcname == "") {
                    swal("Enter DiscountType Name");
                    isvalid = false;
                }

                return isvalid;
            });

            $('#btncancel').on("click", function () {
                document.location = '@Url.Action("Index", "DiscountType")';
            });
</script>

Garments_ERP/Views/DiscountType/CreateDiscountType.cshtml
@model Garments_ERP.Entity.M_DiscountTypeMasterEntity
<style type="text/css">
    .required:after {
        content: "*";
        font-weight: bold;
        color: red;
    }
</style>

<div class="row clearfix">
    <div class="col-md-2">
        <div class="form-group">
            <div class="required">
                <label>Discount Type Name</label>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <div class="form-line">
                @Html.TextBoxFor(model => model.DiscountTypeName, new { @class = "form-control" })
            </div>
            
            @Html.ValidationMessageFor(model => model.DiscountTypeName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <label>DiscountType Short Name</label>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <div class="form-line">
                @Html.TextBoxFor(model => model.ShortName, new { @class = "form-control" })
            </div>
        </div>
    </div>
</div>


<div class="row clearfix">

    <div class="col-md-2">
        <div class="form-group">
            <label>DiscountType Description</label>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <div class="form-line">
                @Html.TextAreaFor(model => model.DiscountTypeDesc, new { @class = "form-control" })
            </div>
        </div>
    </div>

</div>

Garments_ERP/Views/DiscountType/Edit.cshtml
@model Garments_ERP.Entity.M_DiscountTypeMasterEntity
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>>
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<script src="~/Scripts/JqueryUI.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/SelTab.css" rel="stylesheet" />
<link href="~/Content/datepickercs.css" rel="stylesheet" />

@using (Html.BeginForm("Edit", "DiscountType", FormMethod.Post, new { @class = "form-horizontal form-simple", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="titheader">
        <div class="block-header">
            <div class="col-sm-10">
                <div class="HMline"><a href="@Url.Action("Index", "Dashboard")">CSI Master</a>  >  </div>
                <div class="HMline"><a href="@Url.Action("Index", "DiscountType")">Discount Type Detail</a>  >  </div>
                <div class="HMsubline">Edit</div>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-success pull-left" style="margin-right:5px;" id="savedistype">Update</button>
                <button type="button" class="btn btn-danger pull-left" style="margin-right:5px;" id="btncancel" onclick="location.href='@Url.Action("Index", "DiscountType")'">Cancel</button>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <!-- #END# Hover Expand Effect -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="body">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#home_with_icon_title" data-toggle="tab">
                                        <i class="material-icons">home</i> Discount Type Info
                                    </a>
                                </li>

                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade in active" id="home_with_icon_title">
                                    @Html.Partial("CreateDiscountType")
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


}
<script src="~/Scripts/select2.min.js"></script>
<script src=@Url.Content("~/Content/bower_components/jquery/dist/jquery.min.js")></script>
<script src="@Url.Content("~/Content/bower_components/select2/dist/js/select2.full.min.js")"></script>
<script src="@Url.Content("~/Content/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")"></script>

<script src="~/Scripts/SaveCustomer.js"></script>

<script>

    $(document).ready(function () {
        $("#bs_datepicker_component_container > .ui-datepicker-inline").attr("style", "Display:none;");
        $('.select2').select2();
        $('.select2').width("100%");
    });


            $('#savedistype').on("click", function () {
                var isvalid = true;
                var distcname = $('#DiscountTypeName').val();

                if (distcname == "") {
                    swal("Enter DiscountType Name");
                    isvalid = false;
                }

                return isvalid;
            });

            $('#btncancel').on("click", function () {
                document.location = '@Url.Action("Index", "DiscountType")';
            });
</script>

Garments_ERP/Views/DiscountType/Index.cshtml
@model IEnumerable<Garments_ERP.Entity.M_DiscountTypeMasterEntity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdminERP.cshtml";
}

<style>
    #footerExport td {
        cursor: pointer;
        text-align: center;
        border: 1px solid #ccc;
        border: none;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />
<script src="~/Content/sweetalert/sweetalert.min.js"></script>
<script src="~/Content/exportpugin/tableExport.js"></script>
<script src="~/Content/exportpugin/jquery.base64.js"></script>
<script src="~/Content/exportpugin/html2canvas.js"></script>
<script src="~/Content/exportpugin/jspdf/libs/base64.js"></script>
<script src="~/Content/exportpugin/jspdf/libs/sprintf.js"></script>
<script src="~/Content/exportpugin/jspdf/jspdf.js"></script>
<script src="~/Scripts/JqueryUI.js"></script>
<script src="~/Scripts/jquery-ui-1.8.24.js"></script>
<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/SelTab.css" rel="stylesheet" />
<link href="~/Content/datepickercs.css" rel="stylesheet" />

<script>

    $(document).ready(function () {

        var varpdfFontSize = '7';
        $('#exportexcel').bind('click', function (e) {
            $('#example1').tableExport({ type: 'excel', escape: 'false', pdfFontSize: varpdfFontSize });
        });
        $('#exportpdf').bind('click', function (e) {
            $('#example1').tableExport({ type: 'pdf', escape: 'false' });
        });
        $('#exportimage').bind('click', function (e) {
            $('#v').tableExport({ type: 'png', escape: 'false' });
        });
        $('#exportcsv').bind('click', function (e) {
            $('#example1').tableExport({ type: 'csv', escape: 'false' });
        });
        $('#exportppt').bind('click', function (e) {
            $('#example1').tableExport({ type: 'powerpoint', escape: 'false' });
        });
        $('#exportxml').bind('click', function (e) {
            $('#example1').tableExport({ type: 'xml', escape: 'false' });
        });
        $('#exportword').bind('click', function (e) {
            $('#example1').tableExport({ type: 'doc', escape: 'false' });
        });
        $('#exporttxt').bind('click', function (e) {
            $('#example1').tableExport({ type: 'txt', escape: 'false' });
        });

    });

</script>

<div class="titheader">
    <div class="block-header">
        <div class="col-sm-10">
            <div class="HMline"><a href="@Url.Action("Index", "Dashboard")">CSI Master</a>  >  </div>
            <div class="HMsubline">Discount Type Detail</div>
        </div>
        <div class="col-sm-2">
            <a class="btn btn-block btn-success btn-sm" href="@Url.Action("Create", "DiscountType")">Create DiscountType</a>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <!-- #END# Hover Expand Effect -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <div class="col-xs-12 col-sm-6">
                            <h2 class="hedtit">
                                Discount Type Details
                            </h2>
                        </div>

                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 158px;">
                                            DiscountType Name
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 222px;">
                                            DiscountType Desc
                                        </th>

                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 155px;">
                                            Action
                                        </th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        var i = 0;
                                    }
                                    @foreach (var item in @Model)
                                    {
                                        i++;
                                        var edit = "edit" + i;
                                        var itemcategory = "itemcategory" + i;
                                        var itemcategorydesc = "itemcategorydesc" + i;
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">@item.DiscountTypeName</td>
                                            <td>@item.DiscountTypeDesc</td>


                                            <td>
                                                <div>
                                                    <a href="@Url.Action("Edit", "DiscountType", new { id = item.Id })" class="btn  btn-success btn-sm inner" data-original-title="Edit Enquiry">
                                                        <i class="fa fa-fw fa-edit"></i>

                                                    </a>

                                                    <button type="button" id="delete" class="btn btn-danger btn-sm inner" style="width:50px;margin-right:5px;" onclick="deleteDiscountType(@item.Id)"><i class="fa fa-fw fa-remove"></i></button>
                                                </div>
                                            </td>

                                        </tr>
                                    }

                                </tbody>
                            </table>
                            <table>
                                <tr id="footerExport">
                                    <td id="exportexcel"><img src="~/Content/iconsforexport/xls.png" title="Export to Excel" /></td>
                                    <td id="exportpdf"><img src="~/Content/iconsforexport/pdf.png" title="Export to PDF" /></td>
                                    <td id="exportcsv"><img src="~/Content/iconsforexport/csv.png" title="Export to CSV" /></td>
                                    <td id="exportword"><img src="~/Content/iconsforexport/word.png" title="Export to Word" /></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<input type="hidden" id="altmsg" value="@Convert.ToString(TempData["alertmsg"])" />

<script src=@Url.Content("~/Content/bower_components/jquery/dist/jquery.min.js")></script>
<script src="@Url.Content("~/Content/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js")"></script>


<script>
    $(function () {

        $("#bs_datepicker_component_container > .ui-datepicker-inline").attr('style', 'display:none;');
        $("#bs_datepicker_component_container1 > .ui-datepicker-inline").attr('style', 'display:none;');


        $('#example1').DataTable();
        $('#example2').DataTable({
            'paging': true,
            'lengthChange': false,
            'searching': false,
            'ordering': true,
            'info': true,
            'autoWidth': false
        })
        $('.select2').select2();

    });

    $('#bs_datepicker_component_container').datepicker({
        autoclose: true,
        container: '#bs_datepicker_component_container'
    });

    $('#bs_datepicker_component_container1').datepicker({
        autoclose: true,
        container: '#bs_datepicker_component_container1'
    });

    function deleteDiscountType(id) {
        var _id = id;
        var param = { 'id': _id };

        swal({
            title: 'Confirmation',
            text: 'Are You sure delete Discount Type?',
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Confirm',
            confirmButtonColor: '#8CD4F5',
            cancelButtonText: 'Cancel'
        },
         function (isConfirm) {

             if (isConfirm) {

                 $.ajax({
                     type: "POST",
                     url: '@Url.Action("Delete", "DiscountType")',
                     data: JSON.stringify(param),
                     contentType: "application/json; charset=utf-8",
                     dataType: "json",
                     success: function (result) {

                         if (result == true) {
                             //alert("true");
                             window.location.reload();
                         }

                     },
                     failure: function (response) {
                         alert(response.d);
                     }
                 });

             } else {
                 swal("Cancelled", ")", "error");
             }
         });


    }

</script>